/**
 * catalog_definition.json 中 Material 风格枚举名 → @ant-design/icons 导出名。
 * 若 literalString 已是 PascalCase 且存在于图标包，则直接使用，不经此表。
 */
export const LEGACY_MATERIAL_ICON_TO_ANTD: Record<string, string> = {
  accountCircle: 'UserCircleOutlined',
  add: 'PlusOutlined',
  arrowBack: 'ArrowLeftOutlined',
  arrowForward: 'ArrowRightOutlined',
  attachFile: 'PaperClipOutlined',
  calendarToday: 'CalendarOutlined',
  call: 'PhoneOutlined',
  camera: 'CameraOutlined',
  check: 'CheckOutlined',
  close: 'CloseOutlined',
  delete: 'DeleteOutlined',
  download: 'DownloadOutlined',
  edit: 'EditOutlined',
  event: 'CalendarOutlined',
  error: 'CloseCircleOutlined',
  favorite: 'HeartOutlined',
  favoriteOff: 'HeartOutlined',
  folder: 'FolderOutlined',
  help: 'QuestionCircleOutlined',
  home: 'HomeOutlined',
  info: 'InfoCircleOutlined',
  locationOn: 'EnvironmentOutlined',
  lock: 'LockOutlined',
  lockOpen: 'UnlockOutlined',
  mail: 'MailOutlined',
  menu: 'MenuOutlined',
  moreVert: 'MoreOutlined',
  moreHoriz: 'MoreOutlined',
  notificationsOff: 'BellOutlined',
  notifications: 'BellOutlined',
  payment: 'CreditCardOutlined',
  person: 'UserOutlined',
  phone: 'PhoneOutlined',
  photo: 'PictureOutlined',
  print: 'PrinterOutlined',
  refresh: 'ReloadOutlined',
  search: 'SearchOutlined',
  send: 'SendOutlined',
  settings: 'SettingOutlined',
  share: 'ShareAltOutlined',
  shoppingCart: 'ShoppingCartOutlined',
  star: 'StarOutlined',
  starHalf: 'StarOutlined',
  starOff: 'StarOutlined',
  upload: 'UploadOutlined',
  visibility: 'EyeOutlined',
  visibilityOff: 'EyeInvisibleOutlined',
  warning: 'WarningOutlined'
};
